---
title: "ItalyMarriageCaseStudy"
author: "Sarah Boese"
date: "11/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(runjags)
library(tidyverse)
```


```{r}
MarriageSample <- read_csv("ItalyMarriageRates.csv")
head(MarriageSample)

#rates <- MarriageSample$`Rates (per 1000)`

 #ggplot(MarriageSample, aes(x=Year,
 #y='Rates (per 1000)')) +
 #geom_point()
 
 plot(MarriageSample$Year, MarriageSample$`Rates (per 1000)`)
```

```{r}
MarriageSample$group<-0
MarriageSample$Year<-as.integer(MarriageSample$Year)

mean(MarriageSample$`Rates (per 1000)`)

for(i in 1:length(MarriageSample$Year)){
  if(MarriageSample$Year[i]<1939){
    MarriageSample$group[i]=1
  }
  else if(MarriageSample$Year>=1939 && MarriageSample$Year<=1945){
    MarriageSample$group[i]=2
  }
  else{
    MarriageSample$group[i]=3
  }
}

MarriageSample$group_new <- c(rep(1, 3), rep(2, 7), rep(3, 6))
```

```{r}
modelString <-"
model {
## likelihood
for (i in 1:N){
y[i] ~ dnorm(mu_j[group[i]], invsigma2)
}
## priors
for (j in 1:J){
mu_j[j] ~ dnorm(mu, invtau2)
}
invsigma2 ~ dgamma(a_g, b_g)
sigma <- sqrt(pow(invsigma2, -1))
## hyperpriors
mu ~ dnorm(mu0, 1/g0^2)
invtau2 ~ dgamma(a_t, b_t)
tau <- sqrt(pow(invtau2, -1))
}
"
```


```{r}
y = MarriageSample$`Rates (per 1000)`
group = MarriageSample$group_new
N = length(y)
J = length(unique(group))
initsfunction <- function(chain){
.RNG.seed <- c(1,2)[chain]
.RNG.name <- c("base::Super-Duper",
"base::Wichmann-Hill")[chain]
return(list(.RNG.seed=.RNG.seed,
.RNG.name=.RNG.name))
}
the_data <- list("y" = y, "group" = group, "N" = N, "J" = J,
"mu0" = 7.3125, "g0" = 0.5,
"a_t" = 1, "b_t" = 1,
"a_g" = 1, "b_g" = 1)
```

```{r}
posterior <- run.jags(modelString,
                      n.chains = 1,
                      data = the_data,
                      monitor = c("mu", "tau", "mu_j", "sigma"),
                      adapt = 1000,
                      burnin = 5000,
                      sample = 50000,
                      thin = 100,
                      inits = initsfunction)
summary(posterior)
```

```{r}
plot(posterior, vars = "mu_j[3]")
```

